name: 'Build binaries'

on:
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Install dependencies
              run: |
                  sudo apt-get update
                  sudo apt-get install -y \
                      build-essential \
                      cmake \
                      libboost-all-dev \
                      libssl-dev \
                      libzmq3-dev \
                      pkg-config
            - name: Build binaries
              run: |
                  mkdir build
                  cd build
                  cmake ..
                  make